### ISSUE TITLE
Is the JavaScript Testcase Level 3 right?

### ISSUE THREAD

**Issue by ftiefenbach** [Escape-Games-by-Thought-Works/spy-save-places#12]
Hi, thank you for this challenge. I randomly found it on MeetUp and was hooked by the escape room idea! It is really fun. One questions, I am stuck at Level 3. I could imagine that the idea was to call adviceForAlex() instead of convertCoordinates() in the last couple of tests? Please do let me know.

Best regards 
Florian

**Comment by skorpi** [comment]
I stumbled upon the same.
Maybe you have a look at this pull request? https://github.com/Escape-Games-by-Thought-Works/spy-save-places/pull/15

**Comment by Gorcenski** [comment]
Closed with #15
