### ISSUE TITLE
Possible errant array in Ruby test?

### ISSUE THREAD

**Issue by Gorcenski** [Escape-Games-by-Thought-Works/spy-save-places#3]
This line looks like it has both alphanumeric and indexed arrays in it.

https://github.com/Escape-Games-by-Thought-Works/spy-save-places/blob/be86ad3501f29f44c3f299b756d5e7144b6ca413/ruby/run.rb#L47

**Comment by nodepond** [comment]
Oh yes. This was a mistake. Fixed it already.
